# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define :servidorUbuntu do |servidorUbuntu|
      servidorUbuntu.vm.box = "bento/ubuntu-20.04"
      servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
      servidorUbuntu.vm.hostname = "servidorUbuntu"
      servidorUbuntu.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 3072
    end
  end
end

#az functionapp create --name funcAzureTest --storage-account azufuncteststorage --resource-group AzureFunctionsContainers-rg --plan myPremiumPlan --runtime dotnet --deployment-container-image-name omondragon/myprojectnam