version: '3.7'
services:
  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP_USER=prueba
      - FTP_PASSWORD=1234
    volumes:
      - /home/vagrant/:/srv
    expose:
      - 21
    network_mode: host
