version: '3.2'

networks:
  frontend:
    external:
      name: cluster-net 
  backend:

services:
  ################################################################
  # Prometheus 
  #  - corre en el nodo principal
  ################################################################
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    deploy:
      #labels:
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend


  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - 9121:9121
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
      REDIS_PASSWORD: null
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == clienteUbuntu
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == clienteUbuntu
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    deploy:
      placement:
        constraints:
         - node.role == manager

